baseURL = "www.example.com"
languageCode = "en-us"
title = "StackMuncher"
log = true
logFile = "~/projects/stm/about/hugo-serif-theme/log.txt"

[menu]
  # Main Menu
  [[menu.main]]
    name = "Employers"
    url = "/employers/"
      weight = 1

  [[menu.main]]
      name = "Developers"
      url = "/developers/"
      weight = 2

  # Footer Menu
  [[menu.main]]
    name = "About"
    url = "/"
      weight = 3
