baseURL = "//stm-www-7b4g14ydlm.s3-website-us-east-1.amazonaws.com/about/"
languageCode = "en-us"
title = "StackMuncher"
disableKinds = ["taxonomy", "term"]
RelativeURLs=true
CanonifyURLs=true

[deployment]

[[deployment.targets]]
name = "s3"
URL = "s3://stm-www-7b4g14ydlm?region=us-east-1"


[menu]
  # Main Menu
  [[menu.main]]
    name = "Employers"
    url = "/employers/"
      weight = 3

  [[menu.main]]
      name = "Developers"
      url = "/developers/"
      weight = 2

  # Footer Menu
  [[menu.main]]
    name = "About"
    url = "/"
      weight = 1
