baseURL = "www.example.com"
languageCode = "en-us"
title = "Hugo Serif Theme"
log = true
logFile = "~/projects/stm/about/hugo-serif-theme/log.txt"

[params]
  [params.homepage]
    show_call_box = true
    hide_view_all_services = false  # set to true to hide the View All Services button

  [params.logo]
    mobile = "images/logo/logo-mobile.svg"
    desktop = "images/logo/logo.svg"
    desktop_height = "36px"
    alt = "Serif - A Hugo Business Theme"

  [params.homepage_meta_tags]
    meta_description = "Serif is a modern business theme for Hugo. It contains content types for the archetypical business website. The theme is fully responsive, blazing fast and artfully illustrated."
    meta_og_title = "Hugo Serif Theme"
    meta_og_type = "website"
    meta_og_url = "https://hugo-serif.netlify.app"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-serif-theme/master/images/tn.png"
    meta_og_description = "Serif is a modern business theme for Hugo. It contains content types for the archetypical business website. The theme is fully responsive, blazing fast and artfully illustrated."

[menu]
  # Main Menu
  [[menu.main]]
    name = "Employers"
    url = "/employers/"
      weight = 1

  [[menu.main]]
      name = "Developers"
      url = "/developers/"
      weight = 2

  # Footer Menu
  [[menu.main]]
    name = "About"
    url = "/"
      weight = 3
